artifacts_root: artifacts


data_ingestion:
   root_dir: artifacts/data_ingestion
   source_URL: https://drive.google.com/file/d/1CP0xFMgDUhjxOGC6J1rfAnJu_tYKgcND/view?usp=drive_link
   local_data_file: artifacts/data_ingestion/Kidney-ct-scan-image.zip
   unzip_dir: artifacts/data_ingestion


prepare_base_model:
   root_dir: artifacts/prepare_base_model
   base_model_path: artifacts/prepare_base_model/base_model.h5
   updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5



training:
   root_dir: artifacts/training
   trained_model_path: artifacts/training/model.h5
   